name: Trigger Jenkins Build

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: self-hosted
    steps:
      - name: Trigger Jenkins Job
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "$env:JENKINS_URL/job/CypressDemoQA/build" `
            -Method Post `
            -Headers @{Authorization="Basic $([Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes('geovannyjenkins:$env:JENKINS_API_TOKEN')))"}
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
